config/routes.rb
Rails.application.routes.draw do
  resources :expsicos
  resources :exoptos
  resources :pacientes do
    resources :exams do
      resources :exmedicos
      
    end
  end
  
  resources :pacientes do
        resources :exams do
          resources :exfonos
        end
  end
  
    resources :pacientes do
        resources :exams do
          resources :exoptos
        end
  end
  
      resources :pacientes do
        resources :exams do
          resources :expsicos
        end
  end
  
  resources :ant_patologicos
  resources :cities
  resources :states  
  
  end

app/models/paciente.rb
class Paciente < ActiveRecord::Base
  has_many :exams
  
  validates_presence_of :firstname
  validates_presence_of :lastname
  validates_presence_of :address
  validates_presence_of :phone
  validates_presence_of :sexo
  validates_uniqueness_of :cedula
  validates_presence_of :cedula
    def name_with_initial
    "#{firstname} #{lastname}"
  end
end

app/controllers/pacientes_controller.rb
class PacientesController < ApplicationController
  before_action :set_paciente, only: [:show, :edit, :update, :destroy]

  # GET /pacientes
  # GET /pacientes.json
  def index
    @pacientes = Paciente.all
  end

  # GET /pacientes/1
  # GET /pacientes/1.json
  def show
  end

  # GET /pacientes/new
  def new
    @paciente = Paciente.new
  end

  # GET /pacientes/1/edit
  def edit
  end

  # POST /pacientes
  # POST /pacientes.json
  def create
    @paciente = Paciente.new(paciente_params)

    respond_to do |format|
      if @paciente.save
        format.html { redirect_to @paciente, notice: 'Paciente was successfully created.' }
        format.json { render :show, status: :created, location: @paciente }
      else
        format.html { render :new }
        format.json { render json: @paciente.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pacientes/1
  # PATCH/PUT /pacientes/1.json
  def update
    respond_to do |format|
      if @paciente.update(paciente_params)
        format.html { redirect_to @paciente, notice: 'Paciente was successfully updated.' }
        format.json { render :show, status: :ok, location: @paciente }
      else
        format.html { render :edit }
        format.json { render json: @paciente.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pacientes/1
  # DELETE /pacientes/1.json
  def destroy
    @paciente.destroy
    respond_to do |format|
      format.html { redirect_to pacientes_url, notice: 'Paciente was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_paciente
      @paciente = Paciente.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def paciente_params
      params.require(:paciente).permit(:firstname, :lastname, :address, :phone, :mobile, :birthdate, :civilstatus, :cedula, :sexo, :ciudad)
    end
end

app/helpers/pacientes_helper.rb
module PacientesHelper
end

app/views/pacientes/_form.html.erb
<%= form_for(@paciente) do |f| %>
  <% if @paciente.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@paciente.errors.count, "error") %> prohibited this paciente from being saved:</h2>

      <ul>
      <% @paciente.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<input type="file" accept="image/*;capture=camera">

<div class="field">
    <%= f.label :cedula %><br>
    <%= f.text_field :cedula %>
  </div>

  <div class="field">
    <%= f.label :firstname %><br>
    <%= f.text_field :firstname %>
  </div>
  <div class="field">
    <%= f.label :lastname %><br>
    <%= f.text_field :lastname %>
  </div>

<div class="field">
    <%= f.label :sexo %><br>
    <%= f.select :sexo, ['Masculino' , 'Femenino' ] %>
  </div>

  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_area :address %>
  </div>


<p id="state_field">
  <label for="person_city_id">State or Province:</label>
  <%= f.collection_select :city, City.all, :id, :name, :prompt => "Select a city" %>
</p>

  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :mobile %><br>
    <%= f.text_field :mobile %>
  </div>
  <div class="field">
    <%= f.label :birthdate %><br>
    <%= f.date_select :birthdate, { :start_year => 1920 } %>
  </div>
  <div class="field">
    <%= f.label :civilstatus %><br>
    <%= f.select :civilstatus, ['Casado','Soltero','Separado','Union Libre','Viudo'] %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pacientes/edit.html.erb
<% javascript 'dynamic_cities' %>
<h1>Editing Paciente</h1>

<%= render 'form' %>

<%= link_to 'Show', @paciente %> |
<%= link_to 'Back', pacientes_path %>

app/views/pacientes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Pacientes</h1>

<table>
  <thead>
    <tr>
      <th>Cedula</th>
      <th>Firstname</th>
      <th>Lastname</th>
      <th>Sexo</th>
      <th>Address</th>
      <th>Phone</th>
      <th>Mobile</th>
      <th>Birthdate</th>
      <th>Civilstatus</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pacientes.each do |paciente| %>
      <tr>
        <td><%= paciente.cedula %></td>
        <td><%= paciente.firstname %></td>
        <td><%= paciente.lastname %></td>
        <td><%= paciente.sexo %></td>
        <td><%= paciente.address %></td>
        <td><%= paciente.phone %></td>
        <td><%= paciente.mobile %></td>
        <td><%= paciente.birthdate %></td>
        <td><%= paciente.civilstatus %></td>
    
        <td><%= link_to 'Show', paciente %></td>
        <td><%= link_to 'Edit', edit_paciente_path(paciente) %></td>
        <td><%= link_to 'Destroy', paciente, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%= link_to 'View Exams', paciente_exams_path(paciente) %></td>        
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Paciente', new_paciente_path %>

app/views/pacientes/new.html.erb
<% javascript 'dynamic_cities' %>
<h1>New Paciente</h1>

<%= render 'form' %>

<%= link_to 'Back', pacientes_path %>

app/views/pacientes/show.html.erb
<p id="notice"><%= notice %></p>


<p>
  <strong>Cedula:</strong>
  <%= @paciente.cedula %>
</p>

<p>
  <strong>Firstname:</strong>
  <%= @paciente.firstname %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @paciente.lastname %>
</p>

<p>
  <strong>Sexo:</strong>
  <%= @paciente.sexo %>
</p>

<p>
  <strong>Address:</strong>
  <%= @paciente.address %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @paciente.phone %>
</p>

<p>
  <strong>Mobile:</strong>
  <%= @paciente.mobile %>
</p>

<p>
  <strong>Birthdate:</strong>
  <%= @paciente.birthdate %>
</p>

<p>
  <strong>Civilstatus:</strong>
  <%= @paciente.civilstatus %>
</p>



<%= link_to 'Edit', edit_paciente_path(@paciente) %> |
<%= link_to 'Back', pacientes_path %>