config/routes.rb
Rails.application.routes.draw do
  resources :expsicos
  resources :exoptos
  resources :pacientes do
    resources :exams do
      resources :exmedicos
      
    end
  end
  
  resources :pacientes do
        resources :exams do
          resources :exfonos
        end
  end
  
    resources :pacientes do
        resources :exams do
          resources :exoptos
        end
  end
  
      resources :pacientes do
        resources :exams do
          resources :expsicos
        end
  end
  
  resources :ant_patologicos
  resources :cities
  resources :states  
  
  end

app/models/exfono.rb
class Exfono < ActiveRecord::Base
  belongs_to :exam
  before_create :set_defaultvalue
  
  def set_defaultvalue
    self.status = "PENDT"
  end
end

app/controllers/exfonos_controller.rb
class ExfonosController < ApplicationController
  before_action :set_exfono, only: [:show, :edit, :update, :destroy]
  before_action :get_exam
  before_action :get_paciente


  # GET /exfonos
  # GET /exfonos.json
  def index
    @exfonos = Exfono.all
  end

  # GET /exfonos/1
  # GET /exfonos/1.json
  def show
    @exfono = Exfono.find(params[:id])
  end

  # GET /exfonos/new
  def new
    @exfono = Exfono.new
  end

  # GET /exfonos/1/edit
  def edit
  end

  def get_exam
    @exam = Exam.find(params[:exam_id])
  end
  
  def get_paciente
    @paciente = Paciente.find(params[:paciente_id])
  end
  
  # POST /exfonos
  # POST /exfonos.json
  def create
    @exfono = Exfono.new(exfono_params)

    respond_to do |format|
      if @exfono.save
        format.html { redirect_to paciente_exam_exfono_path(@paciente,@exam,@exfono) , notice: 'Exfono was successfully created.' }
        format.json { render :show, status: :created, location: paciente_exam_exfono_path(@paciente,@exam,@exfono) }
      else
        format.html { render :new }
        format.json { render json: @exfono.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /exfonos/1
  # PATCH/PUT /exfonos/1.json
  def update
    respond_to do |format|
      if @exfono.update(exfono_params)
        format.html { redirect_to paciente_exam_exfono_path(@paciente,@exam,@exfono), notice: 'Exfono was successfully updated.' }
        format.json { render :show, status: :ok, location: paciente_exam_exfono_path(@paciente,@exam,@exfono) }
      else
        format.html { render :edit }
        format.json { render json: @exfono.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /exfonos/1
  # DELETE /exfonos/1.json
  def destroy
    @exfono.destroy
    respond_to do |format|
      format.html { redirect_to exfonos_url, notice: 'Exfono was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_exfono
      @exfono = Exfono.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def exfono_params
      params.require(:exfono).permit(:exam_id, :status, :fonq01, :fonq02, :fonq03, :fonq04, :fonq05, :fonq06, :fonq07, :fonq08, :fonq09, :fonq10, :fonq11, :fonq12, :fonq13, :fonq14, :fonq15, :fonq16, :fonq17)
    end
end

app/helpers/exfonos_helper.rb
module ExfonosHelper
end

app/views/exfonos/_form.html.erb
<%= form_for([@paciente,@exam,@exfono]) do |f| %>
  <% if @exfono.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@exfono.errors.count, "error") %> prohibited this exfono from being saved:</h2>

      <ul>
      <% @exfono.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :exam_id %><br>
    <%= f.number_field :exam_id %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.text_field :status %>
  </div>
  <div class="field">
    <%= f.label :fonq01 %><br>
    <%= f.number_field :fonq01 %>
  </div>
  <div class="field">
    <%= f.label :fonq02 %><br>
    <%= f.number_field :fonq02 %>
  </div>
  <div class="field">
    <%= f.label :fonq03 %><br>
    <%= f.number_field :fonq03 %>
  </div>
  <div class="field">
    <%= f.label :fonq04 %><br>
    <%= f.number_field :fonq04 %>
  </div>
  <div class="field">
    <%= f.label :fonq05 %><br>
    <%= f.number_field :fonq05 %>
  </div>
  <div class="field">
    <%= f.label :fonq06 %><br>
    <%= f.number_field :fonq06 %>
  </div>
  <div class="field">
    <%= f.label :fonq07 %><br>
    <%= f.number_field :fonq07 %>
  </div>
  <div class="field">
    <%= f.label :fonq08 %><br>
    <%= f.number_field :fonq08 %>
  </div>
  <div class="field">
    <%= f.label :fonq09 %><br>
    <%= f.number_field :fonq09 %>
  </div>
  <div class="field">
    <%= f.label :fonq10 %><br>
    <%= f.number_field :fonq10 %>
  </div>
  <div class="field">
    <%= f.label :fonq11 %><br>
    <%= f.number_field :fonq11 %>
  </div>
  <div class="field">
    <%= f.label :fonq12 %><br>
    <%= f.number_field :fonq12 %>
  </div>
  <div class="field">
    <%= f.label :fonq13 %><br>
    <%= f.number_field :fonq13 %>
  </div>
  <div class="field">
    <%= f.label :fonq14 %><br>
    <%= f.number_field :fonq14 %>
  </div>
  <div class="field">
    <%= f.label :fonq15 %><br>
    <%= f.number_field :fonq15 %>
  </div>
  <div class="field">
    <%= f.label :fonq16 %><br>
    <%= f.number_field :fonq16 %>
  </div>
  <div class="field">
    <%= f.label :fonq17 %><br>
    <%= f.number_field :fonq17 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/exfonos/edit.html.erb
<h1>Editing Exfono</h1>

<%= render 'form' %>

<%= link_to 'Show', paciente_exam_exfono_path(@paciente,@exam,@exfono) %> |
<%= link_to 'Back', paciente_exams_path(@paciente) %>

app/views/exfonos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Exfonos</h1>

<table>
  <thead>
    <tr>
      <th>Exam</th>
      <th>Status</th>
      <th>Fonq01</th>
      <th>Fonq02</th>
      <th>Fonq03</th>
      <th>Fonq04</th>
      <th>Fonq05</th>
      <th>Fonq06</th>
      <th>Fonq07</th>
      <th>Fonq08</th>
      <th>Fonq09</th>
      <th>Fonq10</th>
      <th>Fonq11</th>
      <th>Fonq12</th>
      <th>Fonq13</th>
      <th>Fonq14</th>
      <th>Fonq15</th>
      <th>Fonq16</th>
      <th>Fonq17</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @exfonos.each do |exfono| %>
      <tr>
        <td><%= exfono.exam_id %></td>
        <td><%= exfono.status %></td>
        <td><%= exfono.fonq01 %></td>
        <td><%= exfono.fonq02 %></td>
        <td><%= exfono.fonq03 %></td>
        <td><%= exfono.fonq04 %></td>
        <td><%= exfono.fonq05 %></td>
        <td><%= exfono.fonq06 %></td>
        <td><%= exfono.fonq07 %></td>
        <td><%= exfono.fonq08 %></td>
        <td><%= exfono.fonq09 %></td>
        <td><%= exfono.fonq10 %></td>
        <td><%= exfono.fonq11 %></td>
        <td><%= exfono.fonq12 %></td>
        <td><%= exfono.fonq13 %></td>
        <td><%= exfono.fonq14 %></td>
        <td><%= exfono.fonq15 %></td>
        <td><%= exfono.fonq16 %></td>
        <td><%= exfono.fonq17 %></td>
        <td><%= link_to 'Show', exfono %></td>
        <td><%= link_to 'Edit', edit_exfono_path(exfono) %></td>
        <td><%= link_to 'Destroy', exfono, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Exfono', new_exfono_path %>

app/views/exfonos/new.html.erb
<h1>New Exfono</h1>

<%= render 'form' %>

<%= link_to 'Back', exfonos_path %>

app/views/exfonos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Exam:</strong>
  <%= @exfono.exam_id %>
</p>

<p>
  <strong>Status:</strong>
  <%= @exfono.status %>
</p>

<p>
  <strong>Fonq01:</strong>
  <%= @exfono.fonq01 %>
</p>

<p>
  <strong>Fonq02:</strong>
  <%= @exfono.fonq02 %>
</p>

<p>
  <strong>Fonq03:</strong>
  <%= @exfono.fonq03 %>
</p>

<p>
  <strong>Fonq04:</strong>
  <%= @exfono.fonq04 %>
</p>

<p>
  <strong>Fonq05:</strong>
  <%= @exfono.fonq05 %>
</p>

<p>
  <strong>Fonq06:</strong>
  <%= @exfono.fonq06 %>
</p>

<p>
  <strong>Fonq07:</strong>
  <%= @exfono.fonq07 %>
</p>

<p>
  <strong>Fonq08:</strong>
  <%= @exfono.fonq08 %>
</p>

<p>
  <strong>Fonq09:</strong>
  <%= @exfono.fonq09 %>
</p>

<p>
  <strong>Fonq10:</strong>
  <%= @exfono.fonq10 %>
</p>

<p>
  <strong>Fonq11:</strong>
  <%= @exfono.fonq11 %>
</p>

<p>
  <strong>Fonq12:</strong>
  <%= @exfono.fonq12 %>
</p>

<p>
  <strong>Fonq13:</strong>
  <%= @exfono.fonq13 %>
</p>

<p>
  <strong>Fonq14:</strong>
  <%= @exfono.fonq14 %>
</p>

<p>
  <strong>Fonq15:</strong>
  <%= @exfono.fonq15 %>
</p>

<p>
  <strong>Fonq16:</strong>
  <%= @exfono.fonq16 %>
</p>

<p>
  <strong>Fonq17:</strong>
  <%= @exfono.fonq17 %>
</p>

<%= link_to 'Edit', edit_paciente_exam_exfono_path(@paciente,@exam,@exfono) %> |
<%= link_to 'Back', paciente_exams_path(@paciente) %>