config/routes.rb
Rails.application.routes.draw do
  resources :expsicos
  resources :exoptos
  resources :pacientes do
    resources :exams do
      resources :exmedicos
      
    end
  end
  
  resources :pacientes do
        resources :exams do
          resources :exfonos
        end
  end
  
    resources :pacientes do
        resources :exams do
          resources :exoptos
        end
  end
  
      resources :pacientes do
        resources :exams do
          resources :expsicos
        end
  end
  
  resources :ant_patologicos
  resources :cities
  resources :states  
  
  end

app/models/exopto.rb
class Exopto < ActiveRecord::Base
   belongs_to :exam
  before_create :set_defaultvalue
  
  def set_defaultvalue
    self.status = "PENDT"
  end
end

app/controllers/exoptos_controller.rb
class ExoptosController < ApplicationController
  before_action :set_exopto, only: [:show, :edit, :update, :destroy]
 before_action :get_exam
  before_action :get_paciente
  
  
 
  # GET /exoptos
  # GET /exoptos.json
  def index
    @exoptos = Exopto.all
  end

  # GET /exoptos/1
  # GET /exoptos/1.json
  def show
    @exoptos = Exopto.find(params[:id])
  end

  # GET /exoptos/new
  def new
    @exopto = Exopto.new
  end

  # GET /exoptos/1/edit
  def edit
  end

   def get_exam
    @exam = Exam.find(params[:exam_id])
  end
  
  def get_paciente
    @paciente = Paciente.find(params[:paciente_id])
  end
  
  
  # POST /exoptos
  # POST /exoptos.json
  def create
    @exopto = Exopto.new(exopto_params)

    respond_to do |format|
      if @exopto.save
        format.html { redirect_to paciente_exam_exopto_path(@paciente,@exam,@exopto), notice: 'Exopto was successfully created.' }
        format.json { render :show, status: :created, location: paciente_exam_exopto_path(@paciente,@exam,@exopto) }
      else
        format.html { render :new }
        format.json { render json: @exopto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /exoptos/1
  # PATCH/PUT /exoptos/1.json
  def update
    respond_to do |format|
      if @exopto.update(exopto_params)
        format.html { redirect_to paciente_exam_exopto_path(@paciente,@exam,@exopto), notice: 'Exopto was successfully updated.' }
        format.json { render :show, status: :ok, location: paciente_exam_exopto_path(@paciente,@exam,@exopto) }
      else
        format.html { render :edit }
        format.json { render json: @exopto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /exoptos/1
  # DELETE /exoptos/1.json
  def destroy
    @exopto.destroy
    respond_to do |format|
      format.html { redirect_to exoptos_url, notice: 'Exopto was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_exopto
      @exopto = Exopto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def exopto_params
      params.require(:exopto).permit(:exam_id, :status, :optq01, :optq02, :optq03, :optq04, :optq05, :optq06, :optq07, :optq08, :optq09, :optq10, :optq11, :optq12, :optq13, :optq14, :optq15, :optq16)
    end
end

app/helpers/exoptos_helper.rb
module ExoptosHelper
end

app/views/exoptos/_form.html.erb
<%= form_for([@paciente,@exam,@exopto]) do |f| %>
  <% if @exopto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@exopto.errors.count, "error") %> prohibited this exopto from being saved:</h2>

      <ul>
      <% @exopto.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :exam_id %><br>
    <%= f.number_field :exam_id %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.text_field :status %>
  </div>
  <div class="field">
    <%= f.label :optq01 %><br>
    <%= f.number_field :optq01 %>
  </div>
  <div class="field">
    <%= f.label :optq02 %><br>
    <%= f.number_field :optq02 %>
  </div>
  <div class="field">
    <%= f.label :optq03 %><br>
    <%= f.number_field :optq03 %>
  </div>
  <div class="field">
    <%= f.label :optq04 %><br>
    <%= f.number_field :optq04 %>
  </div>
  <div class="field">
    <%= f.label :optq05 %><br>
    <%= f.number_field :optq05 %>
  </div>
  <div class="field">
    <%= f.label :optq06 %><br>
    <%= f.number_field :optq06 %>
  </div>
  <div class="field">
    <%= f.label :optq07 %><br>
    <%= f.number_field :optq07 %>
  </div>
  <div class="field">
    <%= f.label :optq08 %><br>
    <%= f.number_field :optq08 %>
  </div>
  <div class="field">
    <%= f.label :optq09 %><br>
    <%= f.number_field :optq09 %>
  </div>
  <div class="field">
    <%= f.label :optq10 %><br>
    <%= f.number_field :optq10 %>
  </div>
  <div class="field">
    <%= f.label :optq11 %><br>
    <%= f.number_field :optq11 %>
  </div>
  <div class="field">
    <%= f.label :optq12 %><br>
    <%= f.number_field :optq12 %>
  </div>
  <div class="field">
    <%= f.label :optq13 %><br>
    <%= f.number_field :optq13 %>
  </div>
  <div class="field">
    <%= f.label :optq14 %><br>
    <%= f.number_field :optq14 %>
  </div>
  <div class="field">
    <%= f.label :optq15 %><br>
    <%= f.number_field :optq15 %>
  </div>
  <div class="field">
    <%= f.label :optq16 %><br>
    <%= f.number_field :optq16 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/exoptos/edit.html.erb
<h1>Editing Exopto</h1>

<%= render 'form' %>

<%= link_to 'Show', paciente_exam_exopto_path(@paciente,@exam,@exopto) %> |
<%= link_to 'Back', paciente_exams_path(@paciente) %>

app/views/exoptos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Exoptos</h1>

<table>
  <thead>
    <tr>
      <th>Exam</th>
      <th>Status</th>
      <th>Optq01</th>
      <th>Optq02</th>
      <th>Optq03</th>
      <th>Optq04</th>
      <th>Optq05</th>
      <th>Optq06</th>
      <th>Optq07</th>
      <th>Optq08</th>
      <th>Optq09</th>
      <th>Optq10</th>
      <th>Optq11</th>
      <th>Optq12</th>
      <th>Optq13</th>
      <th>Optq14</th>
      <th>Optq15</th>
      <th>Optq16</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @exoptos.each do |exopto| %>
      <tr>
        <td><%= exopto.exam_id %></td>
        <td><%= exopto.status %></td>
        <td><%= exopto.optq01 %></td>
        <td><%= exopto.optq02 %></td>
        <td><%= exopto.optq03 %></td>
        <td><%= exopto.optq04 %></td>
        <td><%= exopto.optq05 %></td>
        <td><%= exopto.optq06 %></td>
        <td><%= exopto.optq07 %></td>
        <td><%= exopto.optq08 %></td>
        <td><%= exopto.optq09 %></td>
        <td><%= exopto.optq10 %></td>
        <td><%= exopto.optq11 %></td>
        <td><%= exopto.optq12 %></td>
        <td><%= exopto.optq13 %></td>
        <td><%= exopto.optq14 %></td>
        <td><%= exopto.optq15 %></td>
        <td><%= exopto.optq16 %></td>
        <td><%= link_to 'Show', exopto %></td>
        <td><%= link_to 'Edit', edit_exopto_path(exopto) %></td>
        <td><%= link_to 'Destroy', exopto, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Exopto', new_exopto_path %>

app/views/exoptos/new.html.erb
<h1>New Exopto</h1>

<%= render 'form' %>

<%= link_to 'Back', exoptos_path %>

app/views/exoptos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Exam:</strong>
  <%= @exopto.exam_id %>
</p>

<p>
  <strong>Status:</strong>
  <%= @exopto.status %>
</p>

<p>
  <strong>Optq01:</strong>
  <%= @exopto.optq01 %>
</p>

<p>
  <strong>Optq02:</strong>
  <%= @exopto.optq02 %>
</p>

<p>
  <strong>Optq03:</strong>
  <%= @exopto.optq03 %>
</p>

<p>
  <strong>Optq04:</strong>
  <%= @exopto.optq04 %>
</p>

<p>
  <strong>Optq05:</strong>
  <%= @exopto.optq05 %>
</p>

<p>
  <strong>Optq06:</strong>
  <%= @exopto.optq06 %>
</p>

<p>
  <strong>Optq07:</strong>
  <%= @exopto.optq07 %>
</p>

<p>
  <strong>Optq08:</strong>
  <%= @exopto.optq08 %>
</p>

<p>
  <strong>Optq09:</strong>
  <%= @exopto.optq09 %>
</p>

<p>
  <strong>Optq10:</strong>
  <%= @exopto.optq10 %>
</p>

<p>
  <strong>Optq11:</strong>
  <%= @exopto.optq11 %>
</p>

<p>
  <strong>Optq12:</strong>
  <%= @exopto.optq12 %>
</p>

<p>
  <strong>Optq13:</strong>
  <%= @exopto.optq13 %>
</p>

<p>
  <strong>Optq14:</strong>
  <%= @exopto.optq14 %>
</p>

<p>
  <strong>Optq15:</strong>
  <%= @exopto.optq15 %>
</p>

<p>
  <strong>Optq16:</strong>
  <%= @exopto.optq16 %>
</p>

<%= link_to 'Edit', edit_paciente_exam_exopto_path(@paciente,@exam,@exopto) %> |
<%= link_to 'Back', paciente_exams_path(@paciente) %>