config/routes.rb
Rails.application.routes.draw do
  resources :expsicos
  resources :exoptos
  resources :pacientes do
    resources :exams do
      resources :exmedicos
      
    end
  end
  
  resources :pacientes do
        resources :exams do
          resources :exfonos
        end
  end
  
    resources :pacientes do
        resources :exams do
          resources :exoptos
        end
  end
  
      resources :pacientes do
        resources :exams do
          resources :expsicos
        end
  end
  
  resources :ant_patologicos
  resources :cities
  resources :states  
  
  end

app/models/exam.rb
class Exam < ActiveRecord::Base
  validates_presence_of :paciente_id
  belongs_to :paciente
  has_one :exmedico
  has_one :exfono
  has_one :exopto
  has_one :expsico
  before_create :set_defaultvalues
    before_create :build_default_exams
  
  
  
  def set_defaultvalues
    self.status = "PENDT"
  end
  
  
  
    private
def build_default_exams
  # build default profile instance. Will use default params.
  # The foreign key to the owning User model is set automatically
  build_exmedico
  build_exfono
  build_exopto
  build_expsico
  true # Always return true in callbacks as the normal 'continue' state
       # Assumes that the default_profile can **always** be created.
       # or
       # Check the validation of the profile. If it is not valid, then
       # return false from the callback. Best to use a before_validation 
       # if doing this. View code should check the errors of the child.
       # Or add the child's errors to the User model's error array of the :base
       # error item
end
  
  
end

app/controllers/exams_controller.rb
class ExamsController < ApplicationController
  before_action :set_exam, only: [:show, :edit, :update, :destroy]
  before_action :get_paciente

  

  # GET /exams
  # GET /exams.json
  def index
    @exams = @paciente.exams.all 
  end
  
  def get_paciente
    @paciente = Paciente.find(params[:paciente_id])
  end
  

  
  

  

  # GET /exams/1
  # GET /exams/1.json
  def show
    @exams = @paciente.exams.find(params[:id])
  end

  # GET /exams/new
  def new
    @exam = Exam.new
  end

  # GET /exams/1/edit
  def edit
  end
  

  # POST /exams
  # POST /exams.json
  def create
    @exam = @paciente.exams.new(exam_params)

    
      if @exam.save
        redirect_to [@paciente, @exam]
      else
        render action: "new"
      end
    
  end

  # PATCH/PUT /exams/1
  # PATCH/PUT /exams/1.json
  def update
    respond_to do |format|
      if @exam.update(exam_params)
        format.html { redirect_to @exam, notice: 'Exam was successfully updated.' }
        format.json { render :show, status: :ok, location: @exam }
      else
        format.html { render :edit }
        format.json { render json: @exam.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /exams/1
  # DELETE /exams/1.json
  def destroy
    @exam.destroy
    respond_to do |format|
      format.html { redirect_to exams_url, notice: 'Exam was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_exam
      @exam = Exam.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def exam_params
      params.require(:exam).permit(:paciente_id, :date, :status)
    end
end

app/helpers/exams_helper.rb
module ExamsHelper
end

app/views/exams/_form.html.erb
<%= form_for([@paciente , @exam]) do |f| %>
  <% if @exam.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@exam.errors.count, "error") %> prohibited this exam from being saved:</h2>

      <ul>
      <% @exam.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.label :date %><br>
    <%= f.datetime_select :date %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.text_field :status %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/exams/edit.html.erb
<h1>Editing Exam</h1>

<%= render 'form' %>

<%= link_to 'Show', paciente_exam_path(@paciente,@exam) %> |
<%= link_to 'Back', paciente_exams_path(@paciente) %>

app/views/exams/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Exams</h1>

<table>
  <thead>
    <tr>
      <th>Paciente</th>
      <th>Date</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @exams.each do |exam| %>
      <tr>
        <td><%= link_to exam.paciente.name_with_initial, exam.paciente %></td>
        <td><%= exam.date %></td>
        <td><%= exam.status %></td>
        <td><%= link_to 'Show', paciente_exam_path(@paciente,exam) %></td>
        <td><%= link_to 'Edit', edit_paciente_exam_path(@paciente,exam) %></td>
        <td><%= link_to 'Destroy', paciente_exam_path(@paciente,exam), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%= link_to 'Examen Medico', edit_paciente_exam_exmedico_path(@paciente,exam,exam.exmedico) %>
        <td><%= link_to 'Examen Fonoaudiologico', edit_paciente_exam_exfono_path(@paciente,exam,exam.exfono) %>
        <td><%= link_to 'Examen Optometra', edit_paciente_exam_exopto_path(@paciente,exam,exam.exopto) %>
            <td><%= link_to 'Examen Psicologico', edit_paciente_exam_expsico_path(@paciente,exam,exam.expsico) %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Exam', new_paciente_exam_path(@paciente) %> 

<%= link_to 'back', pacientes_path %> 

app/views/exams/new.html.erb
<h1>New Exam</h1>

<%= render 'form' %>

<%= link_to 'Back', paciente_exams_path(@paciente) %>

app/views/exams/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Paciente:</strong>
  <%= @exam.paciente.name_with_initial %>
</p>

<p>
  <strong>Date:</strong>
  <%= @exam.date %>
</p>

<p>
  <strong>Status:</strong>
  <%= @exam.status %>
</p>

<%= link_to 'Edit', edit_paciente_exam_path(@paciente, @exam) %> |
<%= link_to 'Back', paciente_exams_path(@paciente) %>